// Builds responsive AVIF / WebP / JPEG variants for every photo in
// assets-src/photos and writes a typed manifest to src/data/images.gen.ts.
//
//   npm run images
//
// Crops live here (not in CSS) so that third-party branding, people and
// overlay text are removed from the delivered files themselves.
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC = "assets-src/photos";
const OUT = "public/media/img";
const MANIFEST = "src/data/images.gen.ts";
const WIDTHS = [480, 800, 1200, 1600];

/**
 * Per-image settings.
 *  crop:  { left, top, width, height } in source pixels
 *  focus: CSS object-position for art direction
 */
const CONFIG = {
  "crepe-fragole": {
    // removes the branded latte glass, sugar sachet and table sign
    crop: { left: 0, top: 420, width: 1290, height: 730 },
    focus: "50% 55%",
  },
  "pizza-burrata": {
    // removes the guest in the background and the glass on the right
    crop: { left: 0, top: 150, width: 1170, height: 1539 },
    focus: "45% 60%",
  },
  matcha: {
    // removes the "matcha days / Juni" overlay and the branded biscuit
    crop: { left: 0, top: 0, width: 770, height: 1420 },
    focus: "50% 50%",
  },
  "sala-natale": {
    // removes the birthday balloon on the left
    crop: { left: 250, top: 0, width: 1010, height: 937 },
    focus: "40% 55%",
  },
  "pizze-candela": { focus: "50% 60%" },
  "linguine-mare": { focus: "55% 55%" },
  "fragole-insegna": { focus: "35% 30%" },
  "cheesecake-piazza": { focus: "50% 70%" },
  "antipasti-teller": { focus: "45% 60%" },
  "penne-pesto": { focus: "50% 50%" },
  "salmone-risotto": { focus: "45% 60%" },
  fondo: { focus: "55% 55%" },
  "buffet-antipasti": { focus: "50% 55%" },
  "buffet-frutta": { focus: "50% 60%" },
  "sala-festa": { focus: "50% 60%" },
};

await mkdir(OUT, { recursive: true });
const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort();
const entries = [];

for (const file of files) {
  const name = path.parse(file).name;
  const cfg = CONFIG[name] ?? {};
  let base = sharp(path.join(SRC, file)).rotate();
  if (cfg.crop) base = base.extract(cfg.crop);
  const buf = await base.toBuffer();
  const { width, height } = await sharp(buf).metadata();

  // never upscale: keep only widths below the native size, plus the native size
  const widths = [...WIDTHS.filter((w) => w < width * 0.9), width].filter(
    (w, i, a) => a.indexOf(w) === i,
  );

  for (const w of widths) {
    const img = sharp(buf).resize({ width: w, withoutEnlargement: true });
    await Promise.all([
      img.clone().avif({ quality: 58, effort: 4 }).toFile(`${OUT}/${name}-${w}.avif`),
      img.clone().webp({ quality: 80, effort: 6 }).toFile(`${OUT}/${name}-${w}.webp`),
      img.clone().jpeg({ quality: 82, mozjpeg: true, progressive: true }).toFile(`${OUT}/${name}-${w}.jpg`),
    ]);
  }

  // tiny blurred preview, inlined as the loading placeholder
  const lqip = await sharp(buf).resize(24).blur(1.2).webp({ quality: 40 }).toBuffer();

  entries.push({
    name,
    width,
    height,
    widths,
    focus: cfg.focus ?? "50% 50%",
    lqip: `data:image/webp;base64,${lqip.toString("base64")}`,
  });
  console.log(`${name.padEnd(20)} ${width}x${height}  → ${widths.join(", ")}`);
}

const body = entries
  .map(
    (e) =>
      `  "${e.name}": { src: "media/img/${e.name}", width: ${e.width}, height: ${e.height}, widths: [${e.widths.join(", ")}], focus: "${e.focus}", lqip: "${e.lqip}" },`,
  )
  .join("\n");

await writeFile(
  MANIFEST,
  `// Generated by scripts/optimize-images.mjs — do not edit by hand.
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  widths: number[];
  focus: string;
  lqip: string;
};

export const images = {
${body}
} satisfies Record<string, ImageAsset>;

export type ImageName = keyof typeof images;
`,
);
console.log(`\n${entries.length} images → ${MANIFEST}`);
